server:
  port: 8081

spring:
  r2dbc:
    name: postgres
    username: postgres
    password: postgres
    url: r2dbc:pool:postgresql://localhost:5432
  application:
    name: Webflux
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          push-rate: 1s
          job: ${spring.application.name}
