server:
  port: 8082

spring:
  r2dbc:
    name: postgres
    username: postgres
    password: postgres
    url: r2dbc:pool:postgresql://db:5432
  application:
    name: Kotlin Coroutines
management:
  tracing:
    sampling:
      probability: 1
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          push-rate: 1s
          job: ${spring.application.name}
          base-url: http://pushgateway:9091
          shutdown-operation: put
