server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  threads:
    virtual:
      enabled: true
  application:
    name: Virtual Threads
  session:
    timeout: P1S

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          push-rate: 1s
          job: ${spring.application.name}
